services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./db:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s # Check every 5 seconds
      timeout: 10s # Timeout after 10 seconds
      retries: 30 # Retry up to 30 times
      start_period: 30s # Allow initial start-up time


  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://user:secret@mongodb:27017
